import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Compass, HeartHandshake, Layers3 } from "lucide-react";
import heroImage from "@/assets/education-pathways.jpg";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [{ title: "About EduHub42 | More Than Tutoring" }, { name: "description", content: "Discover EduHub42’s purpose and integrated approach to academic development, education access and career readiness." }, { property: "og:title", content: "About EduHub42 | More Than Tutoring" }, { property: "og:description", content: "An Education Development Enterprise building pathways for lifelong success." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/about" }] }), component: AboutPage });

function AboutPage() { return <>
  <section className="dark-band pt-44 pb-24"><div className="page-container grid items-center gap-10 lg:grid-cols-[1fr_.8fr]"><div><p className="eyebrow">About EduHub42</p><h1 className="section-title mt-4 max-w-3xl">More Than Tutoring.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-primary-foreground/75">We are building an integrated education ecosystem designed to support learners across key stages of their academic, educational and professional journeys.</p></div><img src={heroImage} alt="Connected pathways emerging from an open book" className="aspect-[4/3] w-full rounded-md object-cover" width={1600} height={1104} /></div></section>
  <section className="section-pad"><div className="page-container grid gap-14 lg:grid-cols-2"><div><p className="eyebrow">Our purpose</p><h2 className="section-title mt-4">Transform education. Empower learners. Create pathways.</h2></div><div className="space-y-5 text-base leading-8 text-muted-foreground"><p>EduHub42 exists to help learners move forward with the right academic support, practical guidance and access to opportunity.</p><p>Our work begins in the classroom but does not end there. We connect learning with admissions, development and career readiness so that each step strengthens the next.</p><p>That is what makes EduHub42 an Education Development Enterprise: one organisation, multiple pathways, and a long-term commitment to learner progress.</p></div></div></section>
  <section className="section-pad muted-band"><div className="page-container"><div className="grid gap-6 md:grid-cols-3">{[[Layers3,"Integrated","Support that connects academic, educational and professional development."],[Compass,"Pathway-led","Guidance grounded in where a learner is now and where they want to go."],[HeartHandshake,"Human","A professional, encouraging approach that sees the whole learner."]].map(([Icon,title,text]) => { const I=Icon as typeof Layers3; return <article key={title as string} className="pathway-card"><I className="size-7 text-accent"/><h2 className="mt-6 text-2xl font-bold">{title as string}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{text as string}</p></article>})}</div><div className="mt-12 text-center"><Button asChild size="lg"><Link to="/pillars">Explore our pillars <ArrowRight /></Link></Button></div></div></section>
</> }
