import { createFileRoute } from "@tanstack/react-router";
import { BriefcaseBusiness, GraduationCap, Smartphone } from "lucide-react";
import { CareerForm } from "@/components/forms";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";

const roles=[[GraduationCap,"Become a Tutor","Share your knowledge and support learners.","Tutor"],[BriefcaseBusiness,"Join Our Admin Team","Support the operations and growth of EduHub42.","Administration"],[Smartphone,"Social Media Management","Help manage and grow the EduHub42 digital presence.","Social Media"]] as const;
export const Route = createFileRoute("/careers")({ head: () => ({ meta: [{ title: "Careers at EduHub42 | Join Our Team" }, { name: "description", content: "Explore tutor, administration and social media opportunities with EduHub42." }, { property: "og:title", content: "Careers at EduHub42 | Join Our Team" }, { property: "og:description", content: "Create meaningful impact in education and learner development with EduHub42." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/careers" }] }), component: CareersPage });
function CareersPage(){return <><section className="dark-band pt-44 pb-24"><div className="page-container"><p className="eyebrow">Make an impact</p><h1 className="section-title mt-4">Join the EduHub42 Team</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-primary-foreground/75">Are you passionate about education, student development and creating meaningful impact? Explore opportunities to become part of EduHub42.</p></div></section><section className="section-pad muted-band"><div className="page-container grid gap-6 lg:grid-cols-3">{roles.map(([Icon,title,text,position])=><article key={title} className="pathway-card"><Icon className="size-8 text-accent"/><h2 className="mt-7 text-2xl font-bold">{title}</h2><p className="mt-3 min-h-12 text-sm leading-6 text-muted-foreground">{text}</p><Dialog><DialogTrigger asChild><Button className="mt-7">Apply now</Button></DialogTrigger><DialogContent className="max-h-[92vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>Complete your application and attach your CV.</DialogDescription></DialogHeader><CareerForm position={position}/></DialogContent></Dialog></article>)}</div></section></>}
